version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/django-book
    ports:
      - "8000:8000"
    environment:
      DB_NAME: ${DATABASE_NAME}
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_HOST: pgdb2
    depends_on:
      - pgdb2

  pgdb2:
    image: postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    container_name: pgdb2

volumes:
  pgdbdata:
    driver: local
  djangoappp:
    driver: local